# Generated by Django 4.2.11 on 2024-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_card', '0003_alter_eventdetails_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedetails',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
