# Generated by Django 4.2.11 on 2024-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letter', '0002_coverletter_experience_coverletter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
