# Generated by Django 5.0.3 on 2024-04-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_phone_number', models.CharField(max_length=50)),
                ('host_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_cards.eventdetails')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_cards.hostdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_cards.messagedetails')),
            ],
        ),
    ]
