# Generated by Django 4.2.11 on 2024-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_cards', '0002_alter_eventdetails_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_time',
            field=models.CharField(max_length=100),
        ),
    ]
