# Generated by Django 5.0.3 on 2024-04-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('issuer_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('graduation_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsibilities', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CVResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.certification')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.education')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.language')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.personalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='languages',
            field=models.ManyToManyField(through='cv_resume.PersonalLanguage', to='cv_resume.language'),
        ),
        migrations.CreateModel(
            name='CVSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.cvresume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.skill')),
            ],
        ),
        migrations.AddField(
            model_name='cvresume',
            name='skills',
            field=models.ManyToManyField(through='cv_resume.CVSkill', to='cv_resume.skill'),
        ),
        migrations.AddField(
            model_name='cvresume',
            name='workExperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_resume.workexperience'),
        ),
    ]
