# Generated by Django 4.2.11 on 2024-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_resume', '0002_cvresume_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
