# Generated by Django 4.2.11 on 2024-06-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_resume', '0004_profilephoto_remove_personalinfo_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
