# Generated by Django 4.2.11 on 2024-06-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_resume', '0005_alter_certification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='profile_photo',
        ),
    ]
