# Generated by Django 4.2.11 on 2024-06-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_resume', '0006_remove_personalinfo_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profile_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_resume.profilephoto'),
        ),
    ]
