# Generated by Django 4.2.11 on 2024-06-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_resume', '0008_remove_personalinfo_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvresume',
            old_name='workExperience',
            new_name='work_experience',
        ),
    ]
